[window]
decorations="Full"
[font]
# normal={family="FiraMono Nerd Font",style="Regular"}
normal={family="MesloLGS NF",style="Regular"}
# normal={family="Noto Mono",style="Regular"}
bold={family="MesloLGS NF",style="Bold"}
# bold={family="Noto Mono",style="Bold"}
size=14
[selection]
save_to_clipboard=true
[cursor]
style.blinking="Always"
blink_interval=400
blink_timeout=0
